CREATE DATABASE VISITS
GO

USE VISITS
GO

CREATE TABLE USERS(
ID INT IDENTITY (1,1) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
BIRTH DATETIME NOT NULL,
TYPE INT NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
CAREER VARCHAR(50),
MAIL VARCHAR(50),
PICTURE VARCHAR(500)
)

CREATE TABLE BUILDING(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(50) NOT NULL
)

CREATE TABLE CLASSROOM(
ID INT PRIMARY KEY IDENTITY (1,1),
ID_BUILDING INT FOREIGN KEY REFERENCES BUILDING(ID) ON  DELETE CASCADE NOT NULL,
CAPACITY INT NOT NULL
)

CREATE TABLE REGISTER(
ID INT IDENTITY (1,1) PRIMARY KEY,
ID_USER INT FOREIGN KEY REFERENCES USERS(ID) ON DELETE CASCADE NOT NULL,
ID_BUILDING INT FOREIGN KEY REFERENCES BUILDING(ID) NOT NULL,
ID_CLASSROOM INT FOREIGN KEY REFERENCES CLASSROOM(ID) NOT NULL,
ENTRY DATETIME NOT NULL,
EXIT_TIME DATETIME NOT NULL,
REASON VARCHAR(500) NOT NULL
)
